### ISSUE TITLE
[Bug]: Laravel 11

### ISSUE THREAD

**Issue by ya-zeed** [webplusmultimedia/filament-json-media#4]
### What happened?

I cannot install the plugin with Laravel 11

### How to reproduce the bug

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires webplusm/gallery-json-media * -> satisfiable by webplusm/gallery-json-media[v1.0.0, ..., v1.2.03].
    - webplusm/gallery-json-media[v1.0.0, ..., v1.2.03] require illuminate/contracts ^10.0 -> found illuminate/contracts[v10.0.0, ..., v10.48.7] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require webplusm/gallery-json-media:*" to figure out if any version is installable, or "composer require webplusm/gallery-json-media:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

### Package Version

2

### PHP Version

8.2

### Laravel Version

11

### Which operating systems does with happen with?

macOS

**Comment by webplusmultimedia** [comment]
Unfortunately, for now , you can't install it in Laravel 11, due to the package i use for thumbnails images ([Croppa](https://github.com/BKWLD/croppa)).
I'll probably updated it soon.

**Comment by webplusmultimedia** [comment]
V 2.x fix it. so try it
