### ISSUE TITLE
[Bug]: An error occurred while uploading two pictures.

### ISSUE THREAD

**Issue by TaikingIT** [webplusmultimedia/filament-json-media#5]
### What happened?

GalleryJsonMedia\Form\JsonMediaGallery::GalleryJsonMedia\Form\{closure}(): Argument #1 ($file) must be of type array, Livewire\Features\SupportFileUploads\TemporaryUploadedFile given

### How to reproduce the bug

upload two pictures

### Package Version

1.2

### PHP Version

8.3.3

### Laravel Version

10.48.7

### Which operating systems does with happen with?

Windows

**Comment by webplusmultimedia** [comment]
Did the field cast as array ?

**Comment by webplusmultimedia** [comment]
I'm working on it

**Comment by webplusmultimedia** [comment]
try the v2.x with php 8.2 minimal
