### ISSUE TITLE
[Bug]: maxFiles(1) - Error Max Files reach

### ISSUE THREAD

**Issue by tangjh** [webplusmultimedia/filament-json-media#9]
### What happened?

Get "Max Files reach" error when using  ->maxFiles(1)

### How to reproduce the bug

\GalleryJsonMedia\Form\JsonMediaGallery::make('logo')
    ->minFiles(0)
    ->maxFiles(1)
    ->image()

### Package Version

2.1.1

### PHP Version

8.2

### Laravel Version

11.4

**Comment by artticks** [comment]
when change to maxFiles(2), I can successfully upload and save 2 images.

**Comment by webplusmultimedia** [comment]
thanks for the report. 
2.1.2 fix it
